# Generated by Django 4.2.8 on 2024-01-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0002_alter_prescription_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='image',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='prescription/'),
        ),
    ]
