# Generated by Django 4.2.8 on 2024-01-07 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0003_alter_prescription_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='image',
            new_name='cropped_image',
        ),
    ]
