# Generated by Django 5.0.1 on 2024-01-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0004_rename_image_prescription_cropped_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='cropped_image',
            field=models.ImageField(default=None, null=True, upload_to='images'),
        ),
    ]
